version: '3'
services:
  postgres:
    container_name: "psql"
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=xsolisdb
    volumes:
      - ./service/sql/init.sql:/docker-entrypoint-initdb.d/init_todo.sql
      - ./postgresql/data:/var/lib/postgresql/data
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./service/src:/app/src
    ports:
      - "5000:5000"
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./ui:/app
    ports:
      - "3000:3000"